version: '3'

tasks:
  default:
    desc: Display the help message
    cmds:
      - task --list

  run:
    desc: Run the application
    cmds:
      - go run cmd/sso/main.go --config=./config/local.yaml

  runWithEnv:
    desc: Run the application with config path in env
    cmds:
      - go run cmd/sso/main.go

  runMigrations:
    desc: Run migrations
    cmds:
      - go run ./cmd/migrator --migrations-path=./migrations
